name: ECR Build Caller Workflow
on:
  push:
    # branches:
    #   - main
    # 

jobs:
  call-workflow-in-ecr-template:
    uses: salientmass/github-action-workflows/.github/workflows/ecr-publish.yml@main
